### ISSUE TITLE
This browser or app may not be secure

### ISSUE THREAD

**Issue by SyRoxS1** [wanghaisheng/tiktoka-studio-uploader#48]
### Description

![image](https://github.com/wanghaisheng/tiktoka-studio-uploader/assets/114361806/4a622874-632b-4215-9348-1407b8b4076a)

It seems that the nightly browser is detected as unsafe by google I tried running it by just using onefile-example_youtube.py

**Comment by wanghaisheng** [comment]
are you use proxy or local resident ip?

**Comment by SyRoxS1** [comment]
I'm using local resident ip and I removed the proxy line that was present in the file before running it

**Comment by SyRoxS1** [comment]
And here is the console log if needed : 
------------ False
------------ firefox
default closewhen100percent:go next after copyright check success
publishpolicy:2
CaptionsCertification:0
LicenceType:0
ShortsremixingType:0
CommentsRatingsPolicy:1
DEBUG: whether run in view mode:False
DEBUG: start web page without proxy:
using stealth
stealth is latest
DEBUG: firefox is now running without proxy:
DEBUG: cookies existing:
your should provide a valid cookie file
DEBUG: you can mannually sign in to save credentials for later auto login
====== <class 'tsup.utils.webdriver.playwright_driver_async.PlaywrightAsyncDriver'>
第 1 次初始化浏览器, 端口为:7322
浏览器 正常状态... 2023-06-29 11:58:21
第1次未找到input 密码框!  2023-06-29 11:58:22
第2次未找到input 密码框!  2023-06-29 11:58:23
第3次未找到input 密码框!  2023-06-29 11:58:25
第4次未找到input 密码框!  2023-06-29 11:58:26
第5次未找到input 密码框!  2023-06-29 11:58:28
第6次未找到input 密码框!  2023-06-29 11:58:29
第7次未找到input 密码框!  2023-06-29 11:58:31
6次未找到input 密码框,重新初始化chrome  2023-06-29 11:58:32
current_url: https://bot.sannysoft.com/
youtube 登录失败!!! 2023-06-29 11:58:32
C:\Users\testt\AppData\Local\Programs\Python\Python310\lib\site-packages\tsup-0.1.16-py3.10.egg\tsup\utils\login.py:391: RuntimeWarning: coroutine 'Page.close' was never awaited
  self.page.close()
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
DEBUG: checking login status failed
DEBUG: you can mannually sign in to save credentials for later auto login
DEBUG: could not find sign in button

**Comment by wanghaisheng** [comment]
@SyRoxS1 I have update the code 
if you dont use proxy, now it wont use stealth.js at all
can you test it

**Comment by SyRoxS1** [comment]
I still have the same problem, It seems like its still use stealth even if i dont use proxy at least the console says it :

![image](https://github.com/wanghaisheng/tiktoka-studio-uploader/assets/114361806/204d2d5b-783f-49f9-82c4-597587b02143)

**Comment by SyRoxS1** [comment]
Okay it seems like I got so much things wrong during the process of running getCookie.py now onefile-example_youtube.py does work and without proxys it doesn't use stealth either thank you so much for your time and sorry for the inconvenience

**Comment by wanghaisheng** [comment]
no that is not your part.
I  should fix this unclear issue as soon as possible.
and you can give me more advice from a user perspective 
getCookie is quite simple code you can twist with

**Comment by SyRoxS1** [comment]
So the issue I add is when I read the readme I thaught you didn't need to edit saveCookie.py so I ran it and it only did the checkRequirments() function and not the getCookie one, so when i ran the one-file-youtube.py it didn't find the Cookie needed so I couldn't neither log in, another weird thing is that the getCookie() function doesn't save the Cookie right after I log in my google account it only saves it when I manually close the nightly browser ( does not save if i force close the script from python), and also I had issue with using relative path for the cookie so I just used absolute path and finnaly it worked for me

**Comment by wanghaisheng** [comment]
> after I log in my google account it only saves it when I manually close the nightly browse
I can fix this one
