### ISSUE TITLE
YouTube Visibility Public and Unlist not clickable

### ISSUE THREAD

**Issue by limiao2** [wanghaisheng/tiktoka-studio-uploader#64]
### Checklist

- [X] I'm asking a question and **not** reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/wanghaisheng/tiktoka-studio-uploader#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/wanghaisheng/tiktoka-studio-uploader/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/wanghaisheng/tiktoka-studio-uploader/issues?q=) for similar questions including closed ones

### Question

In youtube_upload.py, around line 848, the button name should be "PUBLIC" instead of "Public".

Secondly, the button click does not work, even "page.get_by_role("radio", name="PUBLIC").is_visible()" is True.

Could you please help resolve this problem? I wonder if this is observed by other users. Thanks in advance!

**Comment by wanghaisheng** [comment]
actually as you can see line 808 ,I have not separate public to   unlisted,public&premiere,public. that means we need 2 more publish policy enum values. 
right now it should only works for public, line 830
can you check this

**Comment by wanghaisheng** [comment]
I have create a new branch  publish policy for this new feature .can you test against 
you can set publish policy to 3 or 4 @limiao2

**Comment by abhishekmj303** [comment]
@wanghaisheng I also encountered this problem. For me this worked:
- change the locator `tp-yt-paper-radio-button:nth-child(1)` to `tp-yt-paper-radio-group` [L813](https://github.com/wanghaisheng/tiktoka-studio-uploader/blob/8ca6e9f2191b81f4ece52ea1b90f53bc18495f3c/tsup/youtube/youtube_upload.py#L813).
- and fix the error in [L822](https://github.com/wanghaisheng/tiktoka-studio-uploader/blob/8ca6e9f2191b81f4ece52ea1b90f53bc18495f3c/tsup/youtube/youtube_upload.py#L822) self.log.debug: `Log.debug() takes 2 positional arguments but 3 were given` by removing the other argument and calling it seperately.

I also suggest that in [L835](https://github.com/wanghaisheng/tiktoka-studio-uploader/blob/8ca6e9f2191b81f4ece52ea1b90f53bc18495f3c/tsup/youtube/youtube_upload.py#L835), atleast you catch the Exception and log it as it can catch any type, it'll be difficult to debug.

**Comment by wanghaisheng** [comment]
@ abhishekmj303  3ks
