### ISSUE TITLE
Youtube 0 views

### ISSUE THREAD

**Issue by romanrsr** [wanghaisheng/tiktoka-studio-uploader#67]
### Checklist

- [X] I'm asking a question and **not** reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/wanghaisheng/tiktoka-studio-uploader#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/wanghaisheng/tiktoka-studio-uploader/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/wanghaisheng/tiktoka-studio-uploader/issues?q=) for similar questions including closed ones

### Question

As you can see, my first 2 videos had more than 100 and 500 views, but then the others had 0 views (1 view was mine). The only thing I see that is different is in Restrictions it says "Shorts policy" in those that have visualizations. Has this happened to anyone else?

![Captura](https://github.com/wanghaisheng/tiktoka-studio-uploader/assets/36116699/16d70eca-857f-48db-9a3a-6f2c36444e57)

**Comment by wanghaisheng** [comment]
sorry  I can not help you about this
