### ISSUE TITLE
examples not working

### ISSUE THREAD

**Issue by nkj2001** [wanghaisheng/tiktoka-studio-uploader#71]
### Checklist

- [X] I'm asking a question and **not** reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/wanghaisheng/tiktoka-studio-uploader#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/wanghaisheng/tiktoka-studio-uploader/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/wanghaisheng/tiktoka-studio-uploader/issues?q=) for similar questions including closed ones

### Question

where is???

from tsup.db.redisdb import RedisDB ???

**Comment by wanghaisheng** [comment]
Just remove unnecessary code again. can you give another try
