### ISSUE TITLE
How to obtain the video URL after successfully uploading a YouTube video?

### ISSUE THREAD

**Issue by kingmacth** [wanghaisheng/tiktoka-studio-uploader#72]
### Checklist

- [X] I'm asking a question and **not** reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/wanghaisheng/tiktoka-studio-uploader#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/wanghaisheng/tiktoka-studio-uploader/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/wanghaisheng/tiktoka-studio-uploader/issues?q=) for similar questions including closed ones

### Question

How to obtain the video URL after successfully uploading a YouTube video?

**Comment by wanghaisheng** [comment]
isok, video_id=upload.upload(
            video_local_path=videopath,
            video_title="instant publish-test-005",
            video_description=video_description,
            thumbnail_local_path=thumbnail_local_path,
            tags=tags,
            publish_policy=1,
        )


this method got 2 return variable, you should get them after success
