### ISSUE TITLE
怎么pip安装呢，没看见什么命令文档啥的

### ISSUE THREAD

**Issue by yibingchaoyue** [wanghaisheng/tiktoka-studio-uploader#84]
### Checklist

- [X] I'm asking a question and **not** reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/wanghaisheng/tiktoka-studio-uploader#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/wanghaisheng/tiktoka-studio-uploader/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/wanghaisheng/tiktoka-studio-uploader/issues?q=) for similar questions including closed ones

### Question

标题

**Comment by wanghaisheng** [comment]
try
pip install upgenius

it may not work though

**Comment by yibingchaoyue** [comment]
有没有youtube上传示例配置文档什么的，安装了咋用

**Comment by wanghaisheng** [comment]
https://github.com/wanghaisheng/tiktoka-studio-uploader/tree/master/docs
@yibingchaoyue
